todo_manager/todo_list/urls.py
from django.urls import path
from . import views

app_name = "todo_list"

urlpatterns = [
    # path("", views.index_view, name="index"),
    path("", views.ToDoIndexView.as_view(), name="index"),
    path("<int:pk>/", views.ToDoDetailView.as_view(), name="detail"),
    path("<int:pk>/update", views.ToDoItemUpdateView.as_view(), name="update"),
    path("<int:pk>/confirm-delete", views.ToDoItemDeleteView.as_view(), name="delete"),
    path("list/", views.ToDoListView.as_view(), name="list"),
    path("done/", views.ToDoListDoneView.as_view(), name="done"),
    path("create/", views.ToDoItemCreateView.as_view(), name="create"),
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("todos/", include("todo_list.urls")),
]

todo_manager/todo_list/models.py
from django.db import models
from django.urls import reverse


class ToDoItem(models.Model):
    class Meta:
        ordering = ("id",)
        verbose_name = "TODO Item"

    title = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=False)
    done = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse(
            viewname="todo_list:detail",
            kwargs={"pk": self.pk},
        )

    def __str__(self):
        return self.title

todo_manager/todo_list/forms.py
from django import forms
from .models import ToDoItem


class ToDoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = (
            "title",
            "description",
        )

        widgets = {
            "description": forms.Textarea(attrs={"cols": 30, "rows": 5}),
        }

        help_texts = {"description": "Enter commentaries"}


class ToDoItemUpdateForm(forms.ModelForm):
    class Meta(ToDoItemCreateForm.Meta):
        fields = (
            "title",
            "description",
            "done",
        )

todo_manager/todo_list/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    DeleteView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from .models import ToDoItem
from .forms import (
    ToDoItemCreateForm,
    ToDoItemUpdateForm,
)


class ToDoIndexView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.all()[:3]


class ToDoListView(ListView):
    model = ToDoItem


class ToDoListDoneView(ListView):
    queryset = ToDoItem.objects.filter(done=True).all()


class ToDoDetailView(DetailView):
    model = ToDoItem


class ToDoItemCreateView(CreateView):
    model = ToDoItem
    form_class = ToDoItemCreateForm


class ToDoItemUpdateView(UpdateView):
    model = ToDoItem
    template_name_suffix = "_update_form"
    form_class = ToDoItemUpdateForm


class ToDoItemDeleteView(DeleteView):
    model = ToDoItem
    template_name_suffix = "_confirm_delete"

    success_url = reverse_lazy("todo_list:list")


# Кастомное поведение пишется для каждого класса
# def get_success_url(self):
#     return reverse(
#         viewname="todo_list:detail",
#         kwargs={"pk": self.object.pk},
#         )

todo_manager/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Base Title {% endblock title %}</title>
  </head>
  <body>
    {% include "components/navbar.html" %}
    {% block body %} Base Body! {% endblock body %}
    <footer>
      &copy; Django Todo App
      {% block footer %}{% endblock footer %}
      
    </footer>
  </body>
</html>

todo_manager/templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url "index" %}">Home</a></li>
    <li><a href="{% url "todo_list:index" %}">Todo List</a></li>
    <li><a href="#">About</a></li>
  </ul>
</nav>

todo_manager/templates/index.html
{% extends "base.html" %}
{% block title %}
  TODO App Index
{% endblock title %}

{% block body %}
<h1>Welcome to our Todo App!</h1>
<h2>Work is in progress!</h2>
<h3>It is {% now "jS F Y" %}</h3>
<div>
  <div>
  <div>
</div>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends "base.html" %}
{% block footer %}
    ToDo list
{% endblock footer %}

todo_manager/todo_list/templates/todo_list/components/todo_items_list.html
<ul>
  {% for todo_item in object_list %}
  <li>
    <a href="{% url 'todo_list:detail' pk=todo_item.pk %}">
      {{todo_item.title}} {% if todo_item.done %} ✅ {% else %} ❌ {% endif %}
    </a>
  </li>
  {% endfor %}
</ul>

todo_manager/todo_list/templates/todo_list/index.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo List App
{% endblock title %}

{% block body %}
    <h1>ToDo List App</h1>
    <ul>
      <li><a href="{% url 'todo_list:list' %}">All Todo items</a></li>
      <li><a href="{% url 'todo_list:done' %}">Done items</a></li>
      <li><a href="{% url 'todo_list:create' %}">Create ToDo item</a></li>
    </ul>
    <h2>ToDos:</h2>
    <ul>
    {% include "todo_list/components/todo_items_list.html" %}
    </ul>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/todoitem_confirm_delete.html
{% extends "todo_list/base.html" %}
{% block title %}
  Confirm Delete ToDo Item #{{ object.id }}
{%endblock title %}

{% block body %}
  <h2>Confirm Delete "{{ object.title }}"</h2>
  <p>
    Are You sure that You want to delete this item 
    <code>{{ object.title }}</code>
  with description <i>{{ object.description }}</i>?
  </p>
  <form method="post">
    {% csrf_token %}
  {{ form }}
    <button type="submit">Delete</button>
  </form>

  <div>
    <a href="{% url 'todo_list:detail' pk=object.pk %}"
    >Back to ToDo Item details</a>
  </div>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo #{{object.pk}}
{% endblock title %}

{% block body %}
    <h3>ToDo</h3>
    <div>
        <div>Title: <strong>{{object.title}}</strong></div>
        <div>Done: <strong>{{object.done}}</strong></div>
        <div>Description: <strong>{{object.description}}</strong></div>
    </div>
    <ul>
      <li>
        <a href="{% url 'todo_list:update' pk=object.pk %}">Update ToDo Item</a>
      </li>
      <li>
        <a href="{% url 'todo_list:delete' pk=object.pk %}">Delete ToDo Item</a>
      </li>
    </ul>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/todoitem_form.html
{% extends "todo_list/base.html" %}

{% block title %}
    Create New Todo item
{% endblock title %}

{% block body %}
  <h3>Create New ToDo: </h3>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Add">
  </form>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/todoitem_list.html
{% extends "todo_list/base.html" %}

{% block title %}
    ToDo List
{% endblock title %}

{% block body %}
    <h3>ToDos</h3>
    {% include "todo_list/components/todo_items_list.html" %}
{% endblock body %}

todo_manager/todo_list/templates/todo_list/todoitem_update_form.html
{% extends "todo_list/base.html" %} 

{% block title %} Update ToDo #{{ object.id }} 
{%endblock title %}

{% block body %}
  <h3>Create New ToDo:</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
  <div>
    <a href="{% url 'todo_list:detail' pk=object.pk %}">Back to ToDo Item details</a>
  </div>

{% endblock body %}